basicapp/urls.py
from django.urls import re_path, include
from basicapp import views
from django.contrib import admin


app_name = 'basicapp'

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^login/$', views.user_login, name='user_login')
]

learning_users/urls.py
from django.contrib import admin
from django.urls import re_path, include
from basicapp import views

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^basicapp/', include('basicapp.urls')),
    re_path(r'logout/$', views.user_logout, name='logout')
]

basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    
    portfolio_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'portfolio_pic')

basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(req):
    return render(req, 'basicapp/index.html')



def register(req):
    registered = False

    if req.method == "POST":
        user_form = UserForm(data=req.POST)
        profile_form = UserProfileInfoForm(data = req.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)

            profile = profile_form.save(commit=False)
            profile.user = user

            # if 'profile_pic' in req.FILES:
            #     profile.profile_pic = req.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(req, 'basicapp/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(req):
    if req.POST == 'POST':
            username = req.POST.get('username')
            password = req.POST.get('password')
            user = authenticate(username=username, password=password)

            if user:
                if user.is_active():
                    login(req,user)
                    print("Its working!")
                    return HttpResponseRedirect(reverse('index'))
                
                else:
                    return HttpResponse("Account is not active")
            else:
                print('Log In Failed')
                return HttpResponse('Invalid Login Details')
    else:
        return render(req, 'basicapp/login.html', {})

@login_required
def user_logout(req):
    logout(req)
    return HttpResponseRedirect(reverse('index'))
        

templates/basicapp/base.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.21.1/babel.min.js"></script>
</head>    

<nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{%url 'index'%}">PMT</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        <li class="active"><a class="navbar-link" href="{% url 'basicapp:register' %}">Register</a></li>

        {% if user.is_authenticated %}
        <li class="active"><a class="navbar-link" href="{% url 'logout' %}">Log Out</a></li>
        {% else %}
        <li class="active"><a class="navbar-link" href="{% url 'basicapp:user_login' %}">Log In</a></li>
     {% endif %}
      </ul>
    </div>
  </nav>



  <div class="container">

    {% block body_block %}
<!-- Every thing outside of the body block will be inherited -->
    {% endblock %}

  </div>
</html>

templates/basicapp/index.html
{% extends 'basicapp/base.html' %}


{% block body_block %}

<div class="jumbotron">
    <h1>Django Registration </h1>
    
</div>

{% endblock %}

templates/basicapp/login.html
{% extends 'basicapp/base.html' %}


{% block body_block %}

<div class="jumbotron">
    <h1>User Log In</h1>

    <form action="{% url 'basicapp:user_login' %}" methon="POST">

        {% csrf_token %}

        <label for="username">Username</label>
        <input name="username" type="text" />

        <label for="password">Password</label>
        <input name="password" type="password" />

<input type="submit" value="Log In" />
    </form>
</div>

{% endblock %}

templates/basicapp/registration.html
{% extends 'basicapp/base.html' %}


{% load staticfiles %}


{% block body_block %}
<div class="jumbotron">
    {% if registered %}
<h1>Thank you for registering!</h1>
    {% endif %}
    <h1>Register Here!</h1>
    <h3> Fill Out Form</h3>

    <form enctype="multipart/form-date" method="POST">
    
    {% csrf_token %}
    {{user_form.as_p}}
    {{profile_form.as_p}}

    <input type="submit" name="" value="Register" />
    </form>
</div>


{% endblock %}